apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movie
  namespace: argocd
spec:
  project: default
  source:
    path: chart
    repoURL: https://github.com/kamil916/movie-depl.git
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: movie
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
