apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "movie-chart.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "movie-chart.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "movie-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}

