apiVersion: v1
kind: Service
metadata:
  name: {{ include "movie-chart.fullname" . }}
spec:
  selector:
    {{- include "movie-chart.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}

